#!/bin/bash

rm temp.init
echo '!' > temp.init
echo '! Gildas to Disk FITS translator' >> temp.init
echo '! <init file generated by bash script> ' >> temp.init
echo '!' >> temp.init
echo 'TASK\FILE "Input Gildas File" IN$ "'$1'" /OLD' >> temp.init
echo 'TASK\FILE "Output FITS file" FITS$ "'$2'" /NEW' >> temp.init
echo 'TASK\INTEGER "Number of bits" NBIT$ -32 /CHOICE 16 32 -32' >> temp.init
echo 'TASK\CHARACTER "Style of FITS file (STANDARD or UVFITS)" STYLE$ "STANDARD"' >> temp.init
echo 'TASK\GO' >> temp.init
